// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChXgoVQFnTx9aHDa1XicnqDXVIr-oHM6A',
    appId: '1:60211596154:web:063db67f900361018524c3',
    messagingSenderId: '60211596154',
    projectId: 'crypto-list-app-5379b',
    authDomain: 'crypto-list-app-5379b.firebaseapp.com',
    storageBucket: 'crypto-list-app-5379b.appspot.com',
    measurementId: 'G-ELT5T8X86G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFx6NRVU0P5PKe4WqXN19cyT6ftpWuVaE',
    appId: '1:60211596154:android:7a30271e99824fff8524c3',
    messagingSenderId: '60211596154',
    projectId: 'crypto-list-app-5379b',
    storageBucket: 'crypto-list-app-5379b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJcZUcQwe--aw7w6JdMQN7Y1qiP81ZQYM',
    appId: '1:60211596154:ios:013314889b2139918524c3',
    messagingSenderId: '60211596154',
    projectId: 'crypto-list-app-5379b',
    storageBucket: 'crypto-list-app-5379b.appspot.com',
    iosBundleId: 'com.example.cryptoCoinList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJcZUcQwe--aw7w6JdMQN7Y1qiP81ZQYM',
    appId: '1:60211596154:ios:7052aeea20dfe4698524c3',
    messagingSenderId: '60211596154',
    projectId: 'crypto-list-app-5379b',
    storageBucket: 'crypto-list-app-5379b.appspot.com',
    iosBundleId: 'com.example.cryptoCoinList.RunnerTests',
  );
}
